parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App\Component\Discount\Model:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Component/Discount/config/doctrine'
                prefix: 'App\Component\Discount\Model'
            App\Component\Order\Model:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Component/Order/config/doctrine'
                prefix: 'App\Component\Order\Model'
            App\Component\Payment\Model:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Component/Payment/config/doctrine'
                prefix: 'App\Component\Payment\Model'
            App\Component\Product\Model:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Component/Product/config/doctrine'
                prefix: 'App\Component\Product\Model'
            App\Component\Shipment\Model:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Component/Shipment/config/doctrine'
                prefix: 'App\Component\Shipment\Model'