image: php:7.3

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -y gnupg2
  - curl --location https://deb.nodesource.com/setup_12.x | bash -
  - apt-get install -yqq git nodejs zip unzip libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libxpm-dev zlib1g-dev libxml2-dev libexpat1-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
  - node -v
  - npm -v
  - docker-php-ext-install mbstring pdo pdo_mysql curl json intl xml zip opcache
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - npm install
  - npm run dev

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: cart
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: cart
  MYSQL_PASSWORD: cart

test:
  stage: test
  script:
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - php bin/console doctrine:migrations:migrate -n -e test
    - php bin/console doctrine:fixtures:load -n -e test
    - php bin/phpunit --coverage-text --colors=never